Repository codestates-seb/seb42_main_020, pull requests merged in 2023-03, with the labels that each got.

#7 Fe/songa to dev
  client/src/App.js
  client/src/Components/CharacterCounter.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Menu.jsx
  client/src/Pages/ExPage.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Style/LoginStyle.js
  client/src/Style/MenuStyle.js
  client/src/atoms/atoms.js
  client/src/variables.css
Labels: 송아

#12 FE/JongWoo to dev
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Style/FooterStyle.js
Labels: 종우

#33 Fe/songa to dev
  client/src/Components/Header/Header.jsx
  client/src/Pages/Login/Login.jsx
  client/src/variables.css
Labels: 송아

#49 Fe/songa to dev : Login, 일반 회원가입, 의사 회원가입-Axios test 코드 작성, 이용약관 유효성 검사 추가
  client/data.json
  client/src/App.js
  client/src/Components/Header/Header.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/HeaderStyle.js
Labels: 송아

#54 Fe/seungmin to Dev
  client/src/Components/AskForm/AskQuestionTitle.jsx
  client/src/Components/AskForm/LocationInput.jsx
  client/src/Components/AskForm/QuestionData.jsx
  client/src/Components/AskForm/TextEditor.jsx
  client/src/Components/AskForm/TypeInput.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Components/ReviewForm/RateStar.jsx
  client/src/Components/ReviewForm/WaitModal.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewPage/Review.jsx
  client/src/Style/AskQuestionStyle.js
  client/src/Style/MakeContentStyle.js
  client/src/Style/NavStyle.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewModalStlye.js
Labels: 승민

#55 FE/JongWoo to dev: Footer UI, Section Post UI 완료
  client/data.json
  client/public/images/Swear.png
  client/src/App.js
  client/src/Components/Footer/Footer.jsx
  client/src/Components/Section/Category.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostListTemplate.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/Section/PostTopic.jsx
  client/src/Components/Section/Section.jsx
  client/src/Style/FooterStyle.js
  client/src/Style/PostCategoryStyle.js
  client/src/Style/PostListStyle.js
  client/src/Style/PostListTemplateStyle.js
  client/src/Style/PostPaginationStyle.js
  client/src/Style/PostSearchStyle.js
  client/src/Style/PostTopicStlye.js
  client/src/Style/SectionStyle.js
Labels: 종우

#58 Fe/songa to dev : Landing 페이지 : GreetingInfo 컴포넌트 구현 및 모달창 오픈 시 스크롤 잠금 hook 생성
  client/data.json
  client/public/images/landing-title.jpg
  client/src/App.js
  client/src/Components/Header/Header.jsx
  client/src/Components/Landing/GreetingInfo.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Landing/Landing.jsx
  client/src/Style/GreetingInfo.js
  client/src/Style/HeaderStyle.js
  client/src/util/useBodyScrollLock.js
Labels: 송아

#62 Fe/seungmin to Dev : 리뷰게시글 상세 페이지 UI 구현
  client/src/App.js
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewDetailStyle.js
Labels: 승민

#72 Fe/songa to dev : Landing 페이지 : ServiceInfo 컴포넌트 구현
  client/public/images/landing-introduce-1.jpg
  client/public/images/landing-introduce-2.jpg
  client/public/images/landing-introduce-3.jpg
  client/src/Components/Landing/GreetingInfo.jsx
  client/src/Components/Landing/ServiceInfo.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Landing/Landing.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/GreetingInfo.js
  client/src/Style/NavStyle.js
  client/src/Style/ServiceInfoStyle.js
  client/src/variables.css
Labels: 송아

#73 Fe/seungmin to Dev : 리뷰 상세 페이지 간단하게 답변 채택, 게시글 수정,삭제 로직 구현
  client/src/App.js
  client/src/Components/AskForm/LocationInput.jsx
  client/src/Components/AskForm/TextEditor.jsx
  client/src/Components/AskForm/TypeInput.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/AskQuestionStyle.js
  client/src/Style/MakeContentStyle.js
  client/src/Style/NavStyle.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReportModalStyle.js
  client/src/Style/ReviewDetailStyle.js
  client/src/Style/ReviewModalStlye.js
Labels: 승민

#78 Fe/songa to dev : Landing 페이지 - OfferInfo 컴포넌트 구현 및 scrollFadein Hook 구현 및 적용
  client/package-lock.json
  client/package.json
  client/src/Pages/Landing/Landing.jsx
  client/src/Style/OfferInfoStyle.js
  client/src/util/useScrollFadeIn.js
Labels: 송아

#80 FE/JongWoo to dev: UserInfo 페이지 및 UI 작업
  client/public/images/care.png
  client/public/images/user-icon.png
  client/src/App.js
  client/src/Components/Section/PostListTemplate.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserMainProfile.jsx
  client/src/Components/UserInfo/UserPost.jsx
  client/src/Components/UserInfo/UserPostCategory.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
  client/src/Components/UserInfo/Userinfo.jsx
  client/src/Style/NavStyle.js
  client/src/Style/PostListTemplateStyle.js
  client/src/Style/UserCardProfileStyle.js
  client/src/Style/UserMainProfileStyle.js
  client/src/Style/UserPostCategoryStyle.js
  client/src/Style/UserPostStyle.js
Labels: 종우

#81 style:App.js-경로 수정
  client/src/App.js
Labels: 송아

#89 FE/Seungmin to Dev : 리뷰 작성 시 병원명 입력을 위한 input tag 생성
  client/src/Components/ReviewForm/HospitalInput.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Style/AskQuestionStyle.js
Labels: 승민

#93 Fe/songa to dev : Hospital Location 컴포넌트, CommentForm 컴포넌트 구현
  client/public/index.html
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/HospitalLocation/HospitalLocation.jsx
  client/src/Style/ServiceInfoStyle.js
Labels: 송아

#96 FE/JongWoo to dev: UserInfo 회원탈퇴 및 로그아웃 Modal/navigate 기능 작업
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Style/UserCardProfileStyle.js
  client/src/Style/UserMainProfileStyle.js
Labels: 종우

#106 Fe/songa to dev
  client/package.json
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/atoms/atoms.js
  client/src/index.js
Labels: 송아

#110 [FE] feat : Login 페이지, Header 컴포넌트- 로그인 상태, 유저 정보
  client/package.json
  client/src/Components/Header/Header.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Pages/Login/Login.jsx
  client/src/atoms/atoms.js
Labels: 송아

#114 [FE] chore : recoil-persist 라이브러리 설치
  client/package.json
  client/src/Pages/Login/Login.jsx
  client/src/atoms/atoms.js
Labels: 송아

#115 Fe/seungmin -> dev : 로그인 상태관리를 이용하여 페이지 내 권한 부여, 서버와 직접 통신하여 리뷰 및 질문 작성 기능 구현
  client/src/Components/AskForm/PostData.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 승민

#117 Fe/seungmin to Dev
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/QuestionDetailStyle.js
Labels: 승민

#118 fix: commit 누락 파일 수정
  client/package-lock.json
  client/package.json
  client/src/Components/Nav/Nav.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Components/ReportModal/ReviewReason.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Style/ReportModalStyle.js
Labels: 승민

#133 refactor : React.lazy 와 Suspense 함수 적용
  client/src/App.js
  client/src/Components/DoctorSignup/DoctorRegiInfoModal.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/Loading/Loading.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Landing/Landing.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/DoctorSignupStyle.js
  client/src/Style/GreetingInfo.js
  client/src/Style/HeaderStyle.js
  client/src/Style/LoginStyle.js
  client/src/Style/SignupStyle.js
  client/src/index.js
  client/src/util/useDidMountEffect.js
  client/src/variables.css
Labels: 송아

#136 [FE] fix : Cannot read properties of undefined error 해결
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 송아

#137 [FE] fix:질문, 리뷰 게시글 좋아요 기능 구현
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 송아

#140 [FE] feat: [UserInfo] 로그아웃, 회원탈퇴 기능 구현
  client/package.json
  client/public/index.html
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserMainProfile.jsx
  client/src/Components/UserInfo/UserPost.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
Labels: 종우

#141 fix: 질문/리뷰 작성 시 textEditor 반대로 입력되는 오류 수정
  client/src/Components/AskForm/TextEditor.jsx
Labels: 승민

#142 feat:MEMBER_STATUS - MEMBER_QUIT 으로 변경으로 회원 탈퇴 구현
  client/src/Components/Header/Header.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/GreetingInfo.js
  client/src/Style/ServiceInfoStyle.js
Labels: 송아

#145 feat:HospitalLocation 컴포넌트- 기능 구현 #91
  client/src/Components/HospitalLocation/HospitalLocation.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 송아

#151 [FE] feat : 로그인, 일반 및 의사 회원가입 - 실패 시 실패 이유 안내창 구현
  client/public/index.html
  client/src/Components/Header/Header.jsx
  client/src/Components/HospitalLocation/HospitalLocation.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/GreetingInfo.js
  client/src/Style/ReviewDetailStyle.js
  client/src/Style/ServiceInfoStyle.js
  client/src/util/useDidMountEffect.js
Labels: 송아

#153 [FE] feat:Enter key를 이용한 로그인 폼 제출 구현 #16
  client/src/Pages/Login/Login.jsx
Labels: 송아

#161 [FE] feat: 관리자 페이지 생성, EditUserInfo 컴포넌트 생성 및 수정 기능 구현
  client/src/Components/UserInfo/EditUserInfo.jsx
  client/src/Components/UserInfo/UserMainProfile.jsx
  client/src/Pages/Admin/Admin.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Signup/Signup.jsx
Labels: 송아

#169 [FE] feat: [Section] PostSearch API 기능 추가
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/Section/Section.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserPostList.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
  client/src/Style/PostCategoryStyle.js
  client/src/Style/PostListStyle.js
  client/src/Style/UserPostCategoryStyle.js
  client/src/Style/UserPostListStyle.js
  client/src/Style/UserPostPaginationStyle.js
Labels: 종우

#167 [FE] feat: 질문 및 댓글 내 좋아요 기능 중복 사용 방지를 위한 error handling 코드 작성, 불필요한 코드 제거 및 중복 코드 제거
  client/src/Components/Answers/Answers.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Style/QuestionDetailStyle.js
Labels: 승민

#170 [FE] fix: 동적 라우팅을 위한 라우팅 경로 수정
  client/src/App.js
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 승민

#171 [FE] feat: Nav 컴포넌트 내 지역 및 진료과목 hover시 상세 목록 렌더링, 질문/리뷰 상세 페이지 내 footer 항목과 section 겹치는 부분 수정, 질문 페이지 내 글 및 댓글 작성자는 본인의 게시글 및 댓글에 좋아요 기능 비활성화
  client/src/App.js
  client/src/Components/Answers/Answers.jsx
  client/src/Components/Nav/LocationButton.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Components/Nav/TypeButton.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Style/AskQuestionStyle.js
  client/src/Style/NavStyle.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewDetailStyle.js
Labels: 승민

#172 [FE] feat : 관리자 로그인 시에만 관리자 메뉴 활성화
  client/src/App.js
  client/src/Components/Header/Header.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Style/HeaderStyle.js
  client/src/atoms/atoms.js
Labels: 송아

#174 [FE] feat: 댓글수정, 신고, 리뷰 상세페이지, 리뷰 작성 후 등록 대기 안내 모달창 구현, 신고 모달 창 및, 채택하기 기능 내 useParams이용하여 path값 수정, 질문 상세 페이지 내 채택된 답변 맨 위로 끌어올림
  client/src/Components/Answers/Answers.jsx
  client/src/Components/AskForm/LocationInput.jsx
  client/src/Components/AskForm/TypeInput.jsx
  client/src/Components/CommentForm/Comment.jsx
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/CommentForm/EditCommentForm.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Components/ReviewForm/WaitModal.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/ReportModalStyle.js
Labels: 승민

#179 [FE] fix: 좋아요, 채택, 수정, 댓글작성 시 새로고침 대신 해당 부분만 재 렌더링 되도록 수정,페이지 내 각종 path값 수정
  client/src/Components/Answers/Answers.jsx
  client/src/Components/CommentForm/EditCommentForm.jsx
  client/src/Components/ReportModal/ReportComment.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
Labels: 승민

#183 [FE] fix: 각종 기능 실행 시 새로고침 대신 해당 부분만 리렌더링하게 기능 수정, UX향상을 위해 모달창 구현
  client/src/Components/Answers/Answers.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/QuestionDetailStyle.js
Labels: 승민

#184 [FE] feat : 엑세스 토큰 검증해서 유요한 토큰 값 리턴하는 hook 생성
  client/src/Components/Login/GoolgeButton.jsx
  client/src/util/Token.js
Labels: 송아

#186 [FE] fix: 각 페이지 내 유효성 검사 추가 및 UX향상을 위한 각종 경고창 및 모달 창 구현
  client/src/Components/Answers/Answers.jsx
  client/src/Components/AskForm/TextEditor.jsx
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/ReportModal/ReportComment.jsx
  client/src/Components/ReviewForm/RateStar.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewDetailStyle.js
Labels: 승민

#190 [FE] style : 의사 회원 인증 안내 이미지 추가 및 각 페이지 반응형 웹 구현
  client/public/images/doctor-signup.jpg
  client/src/Components/DoctorSignup/DoctorRegiInfoModal.jsx
  client/src/Components/Login/GoolgeButton.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/DoctorSignupStyle.js
  client/src/Style/GreetingInfo.js
  client/src/Style/HeaderStyle.js
  client/src/Style/LoginStyle.js
  client/src/Style/OfferInfoStyle.js
  client/src/Style/ServiceInfoStyle.js
Labels: 송아

#191 [FE] chore:html-react-parser 라이브러리 설치
  client/package.json
  client/src/Style/CommentFormStyle.js
Labels: 송아

#192 [FE] feat : 질문, 리뷰 각 게시글 상세 페이지로 이동
  client/public/index.html
  client/src/Components/HospitalLocation/HospitalLocation.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
Labels: 송아

#197 [FE] feat: Nav 항목별 필터링된 게시글 페이지 생성 및 기능 구현
  client/.vscode/settings.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Components/Answers/Answers.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Components/Nav/LocationButton.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Components/Nav/TypeButton.jsx
  client/src/Components/Section/Category.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/Section/PostTopic.jsx
  client/src/Components/Section/Section.jsx
  client/src/Components/UserInfo/UserMainProfile.jsx
  client/src/Components/UserInfo/UserPostList.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/home/AllPost.jsx
  client/src/Pages/home/LocationPosts.jsx
  client/src/Pages/home/QuestionPosts.jsx
  client/src/Pages/home/ReviewPosts.jsx
  client/src/Pages/home/SubjectsPosts.jsx
  client/src/Style/PostListStyle.js
Labels: 종우

#199 [FE] Nav List에 지역 추가
  client/src/Components/CommentForm/EditCommentForm.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/Section.jsx
  client/src/Pages/home/LocationPosts.jsx
  client/src/Style/AskQuestionStyle.js
  client/src/Style/CommentFormStyle.js
  client/src/Style/CommentStyle.js
  client/src/Style/MakeContentStyle.js
  client/src/Style/NavStyle.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReportModalStyle.js
  client/src/Style/ReviewDetailStyle.js
Labels: 승민

#200 [FE] 지역 리스트 경로 path 값 누락 수정
  client/src/Pages/home/LocationPosts.jsx
Labels: 승민

#202 [FE] feat: getAccessTokenFromLocal Hook을 이용하여 Accesstoken 사용하도록 코드 수정
  client/src/Components/Answers/Answers.jsx
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/CommentForm/EditCommentForm.jsx
  client/src/Components/ReportModal/ReportComment.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Components/UserInfo/EditUserInfo.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/util/Token.js
Labels: 승민

#203 [FE] 만료 토큰 갱신 훅 수정 및 페이지네이션 기능 구현 수정
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
  client/src/Style/PostListStyle.js
  client/src/Style/PostPaginationStyle.js
  client/src/util/Token.js
Labels: 송아

#204 [FE] style: 전체 페이지 내 폰트 및 배경색 통일화
  client/src/Style/NavStyle.js
  client/src/Style/PostCategoryStyle.js
  client/src/Style/PostPaginationStyle.js
  client/src/Style/PostTopicStlye.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewDetailStyle.js
  client/src/Style/SectionStyle.js
  client/src/Style/UserCardProfileStyle.js
  client/src/Style/UserInfoStyle.js
  client/src/Style/UserMainProfileStyle.js
  client/src/Style/UserPostCategoryStyle.js
Labels: 승민

#205 [FE] fix: 지역구, 과목별 내 페이지 이동 안되는 것 수정
  client/public/index.html
  client/src/Components/Answers/Answers.jsx
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/Header/Header.jsx
  client/src/Components/HospitalLocation/HospitalLocation.jsx
  client/src/Components/Nav/TypeButton.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Pages/home/LocationPosts.jsx
Labels: 송아

#206 style: 각 페이지 배경색 통일화 및 리뷰 페이지 스타일 수정
  client/src/Components/Section/Section.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Style/ReviewDetailStyle.js
Labels: 승민

#207 [FE] style : 사이트 디자인 통일 작업
  client/src/Components/Answers/Answers.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Style/Answer.js
  client/src/Style/NavStyle.js
  client/src/Style/PostListStyle.js
  client/src/Style/PostPaginationStyle.js
  client/src/Style/QuestionDetailStyle.js
  client/src/Style/ReviewDetailStyle.js
  client/src/Style/SectionStyle.js
Labels: 송아

#208 [FE] fix : 배포 환경에 맞춰 경로 설정
  client/package.json
  client/src/Components/Answers/Answers.jsx
  client/src/Components/CommentForm/CommentForm.jsx
  client/src/Components/CommentForm/EditCommentForm.jsx
  client/src/Components/MakeContents/MakeContents.jsx
  client/src/Components/ReportModal/ReportComment.jsx
  client/src/Components/ReportModal/ReportModal.jsx
  client/src/Components/Section/PostList.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/UserInfo/EditUserInfo.jsx
  client/src/Components/UserInfo/UserCardProfile.jsx
  client/src/Components/UserInfo/UserInfo.jsx
  client/src/Components/UserInfo/UserPostPagination.jsx
  client/src/Pages/Admin/Admin.jsx
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/DoctorSignup/DoctorSignup.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/Login/Login.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/Pages/Review/Review.jsx
  client/src/Pages/ReviewDetail/ReviewDetail.jsx
  client/src/Pages/Signup/Signup.jsx
  client/src/Style/SectionStyle.js
  client/src/util/Token.js
Labels: 송아

#209 [FE] feat: 글 작성 도중 취소 버튼 누를 시 홈페이지 및 해당 게시글 페이지로 이동하도록 기능 구현
  client/src/Pages/AskQuestion/AskQuestion.jsx
  client/src/Pages/EditQuestion/EditQuestion.jsx
  client/src/Pages/Review/Review.jsx
Labels: 승민

#210 [FE] feat: 페이지 이동 시 스클로 최 상단으로 이동시키는 기능 추가, 코드 내 오타 수정
  client/src/Components/ScrollUp/ScrollUp.jsx
  client/src/Pages/QuestionDetail/QuestionDetail.jsx
  client/src/index.js
Labels: 승민

#215 [FE] update: CSS 및 기능 수정 / 삭제
  client/src/Components/Header/Header.jsx
  client/src/Components/Landing/GreetingInfo.jsx
  client/src/Components/Nav/LocationButton.jsx
  client/src/Components/Nav/Nav.jsx
  client/src/Components/Nav/TypeButton.jsx
  client/src/Components/Section/PostPagination.jsx
  client/src/Components/Section/PostSearch.jsx
  client/src/Components/Section/PostTopic.jsx
  client/src/Style/FooterStyle.js
  client/src/Style/GreetingInfo.js
  client/src/Style/HeaderStyle.js
  client/src/Style/LoginStyle.js
  client/src/Style/OfferInfoStyle.js
  client/src/Style/PostPaginationStyle.js
  client/src/Style/SectionStyle.js
  client/src/Style/ServiceInfoStyle.js
Labels: 종우

#216 [FE] style: 게시글 작성 페이지 내 높이 값 조절
  client/src/Style/AskQuestionStyle.js
Labels: 승민

#217 [FE] style:index.html-description 수정
  client/public/index.html
  client/src/Style/HeaderStyle.js
Labels: 송아
